#############################################################################
# Generated by PAGE version 4.9
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
#############################################################################
# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font10
vTcl:font:add_font \
    "-family {Segoe UI} -size 10 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font9
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    set site_3_0 $base.lab38
    set site_3_0 $base.lab39
    set site_3_0 $base.lab40
    set site_3_0 $base.lab41
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 888x700+237+0
    update
    # set in toplevel.wgt.
    global vTcl
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1362 741
    wm minsize $top 888 700
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel 1"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    labelframe $top.lab38 \
        -font $::vTcl(fonts,vTcl:font10,object) -foreground black \
        -text {Forecaster's Input} -background {#d9d9d9} -height 655 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 380 
    vTcl:DefineAlias "$top.lab38" "Labelframe1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab38
    label $site_3_0.lab43 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Onset of Rain} 
    vTcl:DefineAlias "$site_3_0.lab43" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab44 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#808080} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {(DDMMYY hhmm)} 
    vTcl:DefineAlias "$site_3_0.lab44" "Label2" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent45 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable rain_onset 
    vTcl:DefineAlias "$site_3_0.ent45" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab46 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Period of Heaviest Rain} 
    vTcl:DefineAlias "$site_3_0.lab46" "Label3" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab47 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {Start Time} 
    vTcl:DefineAlias "$site_3_0.lab47" "Label4" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab48 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#808080} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {(DDMMYY hhmm)} 
    vTcl:DefineAlias "$site_3_0.lab48" "Label5" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent49 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable heaviest_start 
    vTcl:DefineAlias "$site_3_0.ent49" "Entry2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab52 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {End Time} 
    vTcl:DefineAlias "$site_3_0.lab52" "Label6" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab53 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#808080} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {(DDMMYY hhmm)} 
    vTcl:DefineAlias "$site_3_0.lab53" "Label7" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent54 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable heaviest_end 
    vTcl:DefineAlias "$site_3_0.ent54" "Entry3" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab55 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Affected Areas} 
    vTcl:DefineAlias "$site_3_0.lab55" "Label8" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_3_0.che56 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text North -variable north 
    vTcl:DefineAlias "$site_3_0.che56" "Checkbutton1" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_3_0.che57 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text South -variable south 
    vTcl:DefineAlias "$site_3_0.che57" "Checkbutton2" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_3_0.che58 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text East -variable east 
    vTcl:DefineAlias "$site_3_0.che58" "Checkbutton3" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_3_0.che59 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text West -variable west 
    vTcl:DefineAlias "$site_3_0.che59" "Checkbutton4" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_3_0.che61 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text Central -variable central 
    vTcl:DefineAlias "$site_3_0.che61" "Checkbutton5" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_3_0.che62 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text Many -variable many 
    vTcl:DefineAlias "$site_3_0.che62" "Checkbutton6" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_3_0.che64 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text Most -variable most 
    vTcl:DefineAlias "$site_3_0.che64" "Checkbutton7" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab65 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Cause of Weather} 
    vTcl:DefineAlias "$site_3_0.lab65" "Label9" vTcl:WidgetProc "Toplevel1" 1
    text $site_3_0.tex66 \
        -background white -font TkTextFont -foreground black -height 74 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -undo 1 -width 354 -wrap word 
    .top37.lab38.tex66 configure -font TkTextFont
    .top37.lab38.tex66 insert end text
    vTcl:DefineAlias "$site_3_0.tex66" "Text1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab67 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Flood Reports from Police/PUB} 
    vTcl:DefineAlias "$site_3_0.lab67" "Label10" vTcl:WidgetProc "Toplevel1" 1
    text $site_3_0.tex68 \
        -background white -font TkTextFont -foreground black -height 54 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -undo 1 -width 354 -wrap word 
    .top37.lab38.tex68 configure -font TkTextFont
    .top37.lab38.tex68 insert end text
    vTcl:DefineAlias "$site_3_0.tex68" "Text2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab69 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Forecast 
    vTcl:DefineAlias "$site_3_0.lab69" "Label11" vTcl:WidgetProc "Toplevel1" 1
    text $site_3_0.tex70 \
        -background white -font TkTextFont -foreground black -height 44 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -undo 1 -width 354 -wrap word 
    .top37.lab38.tex70 configure -font TkTextFont
    .top37.lab38.tex70 insert end text
    vTcl:DefineAlias "$site_3_0.tex70" "Text3" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab71 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Remarks 
    vTcl:DefineAlias "$site_3_0.lab71" "Label12" vTcl:WidgetProc "Toplevel1" 1
    text $site_3_0.tex72 \
        -background white -font TkTextFont -foreground black -height 44 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -undo 1 -width 354 -wrap word 
    .top37.lab38.tex72 configure -font TkTextFont
    .top37.lab38.tex72 insert end text
    vTcl:DefineAlias "$site_3_0.tex72" "Text4" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_3_0.tCo37 \
        -textvariable cause_selected -width 214 -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo37" "TCombobox1" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab43 \
        -in $site_3_0 -x 10 -y 20 -anchor nw -bordermode ignore 
    place $site_3_0.lab44 \
        -in $site_3_0 -x 110 -y 20 -anchor nw -bordermode ignore 
    place $site_3_0.ent45 \
        -in $site_3_0 -x 230 -y 20 -width 134 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab46 \
        -in $site_3_0 -x 10 -y 60 -anchor nw -bordermode ignore 
    place $site_3_0.lab47 \
        -in $site_3_0 -x 10 -y 90 -anchor nw -bordermode ignore 
    place $site_3_0.lab48 \
        -in $site_3_0 -x 100 -y 90 -anchor nw -bordermode ignore 
    place $site_3_0.ent49 \
        -in $site_3_0 -x 230 -y 90 -width 134 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab52 \
        -in $site_3_0 -x 10 -y 110 -anchor nw -bordermode ignore 
    place $site_3_0.lab53 \
        -in $site_3_0 -x 100 -y 110 -anchor nw -bordermode ignore 
    place $site_3_0.ent54 \
        -in $site_3_0 -x 230 -y 110 -width 134 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab55 \
        -in $site_3_0 -x 10 -y 150 -anchor nw -bordermode ignore 
    place $site_3_0.che56 \
        -in $site_3_0 -x 10 -y 180 -anchor nw -bordermode ignore 
    place $site_3_0.che57 \
        -in $site_3_0 -x 80 -y 180 -anchor nw -bordermode ignore 
    place $site_3_0.che58 \
        -in $site_3_0 -x 150 -y 180 -anchor nw -bordermode ignore 
    place $site_3_0.che59 \
        -in $site_3_0 -x 220 -y 180 -anchor nw -bordermode ignore 
    place $site_3_0.che61 \
        -in $site_3_0 -x 290 -y 180 -anchor nw -bordermode ignore 
    place $site_3_0.che62 \
        -in $site_3_0 -x 120 -y 200 -anchor nw -bordermode ignore 
    place $site_3_0.che64 \
        -in $site_3_0 -x 180 -y 200 -anchor nw -bordermode ignore 
    place $site_3_0.lab65 \
        -in $site_3_0 -x 10 -y 240 -anchor nw -bordermode ignore 
    place $site_3_0.tex66 \
        -in $site_3_0 -x 10 -y 270 -width 354 -relwidth 0 -height 74 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab67 \
        -in $site_3_0 -x 10 -y 360 -anchor nw -bordermode ignore 
    place $site_3_0.tex68 \
        -in $site_3_0 -x 10 -y 390 -width 354 -relwidth 0 -height 54 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab69 \
        -in $site_3_0 -x 10 -y 460 -anchor nw -bordermode ignore 
    place $site_3_0.tex70 \
        -in $site_3_0 -x 10 -y 490 -width 354 -relwidth 0 -height 44 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab71 \
        -in $site_3_0 -x 10 -y 550 -anchor nw -bordermode ignore 
    place $site_3_0.tex72 \
        -in $site_3_0 -x 10 -y 580 -width 354 -relwidth 0 -height 44 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tCo37 \
        -in $site_3_0 -x 150 -y 240 -width 214 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    labelframe $top.lab39 \
        -font $::vTcl(fonts,vTcl:font10,object) -foreground black \
        -text {Date and Time} -background {#d9d9d9} -height 335 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 200 
    vTcl:DefineAlias "$top.lab39" "Labelframe2" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab39
    label $site_3_0.lab73 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Date 
    vTcl:DefineAlias "$site_3_0.lab73" "Label13" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab74 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#808080} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text (DDMMYY) 
    vTcl:DefineAlias "$site_3_0.lab74" "Label14" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent75 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable date 
    vTcl:DefineAlias "$site_3_0.ent75" "Entry4" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab76 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Past 3 Hours} 
    vTcl:DefineAlias "$site_3_0.lab76" "Label15" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_3_0.che77 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -variable past_3_hours 
    vTcl:DefineAlias "$site_3_0.che77" "Checkbutton8" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab78 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Time Filter} 
    vTcl:DefineAlias "$site_3_0.lab78" "Label16" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_3_0.che79 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -variable time_filter 
    vTcl:DefineAlias "$site_3_0.che79" "Checkbutton9" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab80 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {Filter Start} 
    vTcl:DefineAlias "$site_3_0.lab80" "Label17" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab81 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#808080} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {(DDMMYY hhmm)} 
    vTcl:DefineAlias "$site_3_0.lab81" "Label18" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent82 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable filter_start 
    vTcl:DefineAlias "$site_3_0.ent82" "Entry5" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab83 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {Filter End} 
    vTcl:DefineAlias "$site_3_0.lab83" "Label19" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab84 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#808080} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {(DDMMYY hhmm)} 
    vTcl:DefineAlias "$site_3_0.lab84" "Label20" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent85 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable filter_end 
    vTcl:DefineAlias "$site_3_0.ent85" "Entry6" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab86 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Issue Time} 
    vTcl:DefineAlias "$site_3_0.lab86" "Label21" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent87 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable issue_time 
    vTcl:DefineAlias "$site_3_0.ent87" "Entry7" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab88 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#808080} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {(DDMMYY hhmm)} 
    vTcl:DefineAlias "$site_3_0.lab88" "Label22" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab73 \
        -in $site_3_0 -x 10 -y 20 -anchor nw -bordermode ignore 
    place $site_3_0.lab74 \
        -in $site_3_0 -x 60 -y 20 -anchor nw -bordermode ignore 
    place $site_3_0.ent75 \
        -in $site_3_0 -x 10 -y 50 -anchor nw -bordermode ignore 
    place $site_3_0.lab76 \
        -in $site_3_0 -x 10 -y 90 -anchor nw -bordermode ignore 
    place $site_3_0.che77 \
        -in $site_3_0 -x 110 -y 90 -anchor nw -bordermode ignore 
    place $site_3_0.lab78 \
        -in $site_3_0 -x 10 -y 130 -anchor nw -bordermode ignore 
    place $site_3_0.che79 \
        -in $site_3_0 -x 110 -y 130 -anchor nw -bordermode ignore 
    place $site_3_0.lab80 \
        -in $site_3_0 -x 10 -y 160 -anchor nw -bordermode ignore 
    place $site_3_0.lab81 \
        -in $site_3_0 -x 80 -y 160 -anchor nw -bordermode ignore 
    place $site_3_0.ent82 \
        -in $site_3_0 -x 10 -y 180 -anchor nw -bordermode ignore 
    place $site_3_0.lab83 \
        -in $site_3_0 -x 10 -y 200 -anchor nw -bordermode ignore 
    place $site_3_0.lab84 \
        -in $site_3_0 -x 80 -y 200 -anchor nw -bordermode ignore 
    place $site_3_0.ent85 \
        -in $site_3_0 -x 10 -y 220 -anchor nw -bordermode ignore 
    place $site_3_0.lab86 \
        -in $site_3_0 -x 10 -y 260 -anchor nw -bordermode ignore 
    place $site_3_0.ent87 \
        -in $site_3_0 -x 10 -y 290 -anchor nw -bordermode ignore 
    place $site_3_0.lab88 \
        -in $site_3_0 -x 80 -y 260 -anchor nw -bordermode ignore 
    labelframe $top.lab40 \
        -font $::vTcl(fonts,vTcl:font10,object) -foreground black \
        -text {Stations and Criteria} -background {#d9d9d9} -height 335 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 200 
    vTcl:DefineAlias "$top.lab40" "Labelframe3" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab40
    label $site_3_0.lab89 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Criteria 
    vTcl:DefineAlias "$site_3_0.lab89" "Label23" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab90 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#808080} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {(in mm or km/h)} 
    vTcl:DefineAlias "$site_3_0.lab90" "Label24" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab91 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {30min Rainfall >=} 
    vTcl:DefineAlias "$site_3_0.lab91" "Label25" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent92 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable criteria_30min 
    vTcl:DefineAlias "$site_3_0.ent92" "Entry8" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab93 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {60min Rainfall >=} 
    vTcl:DefineAlias "$site_3_0.lab93" "Label26" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent94 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable criteria_60min 
    vTcl:DefineAlias "$site_3_0.ent94" "Entry9" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab95 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {Wind Gusts >} 
    vTcl:DefineAlias "$site_3_0.lab95" "Label27" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent96 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable criteria_wind_gusts 
    vTcl:DefineAlias "$site_3_0.ent96" "Entry10" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab97 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Stations to be Excluded} 
    vTcl:DefineAlias "$site_3_0.lab97" "Label28" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab98 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#808080} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left \
        -text {(use "; " to seperate two or more stations)} -wraplength 190 
    vTcl:DefineAlias "$site_3_0.lab98" "Label29" vTcl:WidgetProc "Toplevel1" 1
    text $site_3_0.tex99 \
        -background white -font TkTextFont -foreground black -height 74 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -undo 1 -width 174 -wrap word 
    .top37.lab40.tex99 configure -font TkTextFont
    .top37.lab40.tex99 insert end text
    vTcl:DefineAlias "$site_3_0.tex99" "Text5" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab37 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Ad-hoc Request} 
    vTcl:DefineAlias "$site_3_0.lab37" "Label38" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_3_0.che38 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -variable adhoc_request 
    vTcl:DefineAlias "$site_3_0.che38" "Checkbutton10" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab89 \
        -in $site_3_0 -x 10 -y 20 -anchor nw -bordermode ignore 
    place $site_3_0.lab90 \
        -in $site_3_0 -x 70 -y 20 -anchor nw -bordermode ignore 
    place $site_3_0.lab91 \
        -in $site_3_0 -x 10 -y 50 -anchor nw -bordermode ignore 
    place $site_3_0.ent92 \
        -in $site_3_0 -x 130 -y 50 -width 54 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab93 \
        -in $site_3_0 -x 10 -y 70 -anchor nw -bordermode ignore 
    place $site_3_0.ent94 \
        -in $site_3_0 -x 130 -y 70 -width 54 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab95 \
        -in $site_3_0 -x 10 -y 90 -anchor nw -bordermode ignore 
    place $site_3_0.ent96 \
        -in $site_3_0 -x 130 -y 90 -width 54 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab97 \
        -in $site_3_0 -x 10 -y 130 -anchor nw -bordermode ignore 
    place $site_3_0.lab98 \
        -in $site_3_0 -x 10 -y 160 -anchor nw -bordermode ignore 
    place $site_3_0.tex99 \
        -in $site_3_0 -x 10 -y 200 -width 174 -relwidth 0 -height 74 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab37 \
        -in $site_3_0 -x 10 -y 290 -anchor nw -bordermode ignore 
    place $site_3_0.che38 \
        -in $site_3_0 -x 120 -y 290 -anchor nw -bordermode ignore 
    labelframe $top.lab41 \
        -font $::vTcl(fonts,vTcl:font10,object) -foreground black \
        -text {URL or Path} -background {#d9d9d9} -height 225 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 420 
    vTcl:DefineAlias "$top.lab41" "Labelframe4" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab41
    label $site_3_0.lab101 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {URL or Path} 
    vTcl:DefineAlias "$site_3_0.lab101" "Label30" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab102 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {Daily Rainfall} 
    vTcl:DefineAlias "$site_3_0.lab102" "Label31" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab103 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {60min Rainfall} 
    vTcl:DefineAlias "$site_3_0.lab103" "Label32" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab104 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {60min Rainfall (Past 3 Hours)} 
    vTcl:DefineAlias "$site_3_0.lab104" "Label33" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab105 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {30min Rainfall} 
    vTcl:DefineAlias "$site_3_0.lab105" "Label34" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab107 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {30min Rainfall (Past 3 Hours)} 
    vTcl:DefineAlias "$site_3_0.lab107" "Label35" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab108 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {Wind Gusts} 
    vTcl:DefineAlias "$site_3_0.lab108" "Label36" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent109 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable url_daily_rainfall 
    vTcl:DefineAlias "$site_3_0.ent109" "Entry11" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent110 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable url_60min_rainfall 
    vTcl:DefineAlias "$site_3_0.ent110" "Entry12" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent111 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable url_60min_rainfall_past_3hrs 
    vTcl:DefineAlias "$site_3_0.ent111" "Entry13" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent112 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable url_30min_rainfall 
    vTcl:DefineAlias "$site_3_0.ent112" "Entry14" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent113 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable url_30min_rainfall_past_3hrs 
    vTcl:DefineAlias "$site_3_0.ent113" "Entry15" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent114 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable url_wind_gusts 
    vTcl:DefineAlias "$site_3_0.ent114" "Entry16" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab117 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {Monthly Statistics} 
    vTcl:DefineAlias "$site_3_0.lab117" "Label37" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent118 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable path_monthly_statistics 
    vTcl:DefineAlias "$site_3_0.ent118" "Entry17" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab101 \
        -in $site_3_0 -x 10 -y 20 -anchor nw -bordermode ignore 
    place $site_3_0.lab102 \
        -in $site_3_0 -x 10 -y 50 -anchor nw -bordermode ignore 
    place $site_3_0.lab103 \
        -in $site_3_0 -x 10 -y 70 -anchor nw -bordermode ignore 
    place $site_3_0.lab104 \
        -in $site_3_0 -x 10 -y 90 -anchor nw -bordermode ignore 
    place $site_3_0.lab105 \
        -in $site_3_0 -x 10 -y 110 -anchor nw -bordermode ignore 
    place $site_3_0.lab107 \
        -in $site_3_0 -x 10 -y 130 -anchor nw -bordermode ignore 
    place $site_3_0.lab108 \
        -in $site_3_0 -x 10 -y 150 -anchor nw -bordermode ignore 
    place $site_3_0.ent109 \
        -in $site_3_0 -x 190 -y 50 -width 214 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent110 \
        -in $site_3_0 -x 190 -y 70 -width 214 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent111 \
        -in $site_3_0 -x 190 -y 90 -width 214 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent112 \
        -in $site_3_0 -x 190 -y 110 -width 214 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent113 \
        -in $site_3_0 -x 190 -y 130 -width 214 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent114 \
        -in $site_3_0 -x 190 -y 150 -width 214 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab117 \
        -in $site_3_0 -x 10 -y 170 -anchor nw -bordermode ignore 
    place $site_3_0.ent118 \
        -in $site_3_0 -x 190 -y 170 -width 214 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    button $top.but115 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Configure 
    vTcl:DefineAlias "$top.but115" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but116 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Generate 
    vTcl:DefineAlias "$top.but116" "Button2" vTcl:WidgetProc "Toplevel1" 1
    menu $top.m38 \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab38 \
        -in $top -x 30 -y 20 -width 380 -relwidth 0 -height 655 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab39 \
        -in $top -x 430 -y 20 -width 200 -relwidth 0 -height 335 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab40 \
        -in $top -x 650 -y 20 -width 200 -relwidth 0 -height 335 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab41 \
        -in $top -x 430 -y 370 -width 420 -relwidth 0 -height 225 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.but115 \
        -in $top -x 580 -y 620 -width 128 -relwidth 0 -height 38 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but116 \
        -in $top -x 720 -y 620 -width 128 -relwidth 0 -height 38 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top37

